{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "bb6063bc-cf37-49df-b4a4-054b0551bece",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'data_preparation'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[1], line 22\u001b[0m\n\u001b[0;32m     19\u001b[0m warnings\u001b[38;5;241m.\u001b[39mfilterwarnings(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mignore\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m     21\u001b[0m \u001b[38;5;66;03m# Import our custom modules\u001b[39;00m\n\u001b[1;32m---> 22\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mdata_preparation\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m InvoiceDataPreparation\n\u001b[0;32m     23\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mtrend_analysis\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m ExpenseTrendAnalyzer\n\u001b[0;32m     24\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mvendor_segmentation\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m VendorSegmentation\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'data_preparation'"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "MAIN EXECUTION SCRIPT\n",
    "AINextBill Technology - Purchase Invoice Analysis\n",
    "\n",
    "This is the master script that runs the complete analysis pipeline:\n",
    "1. Data Preparation\n",
    "2. Expense Trend Analysis\n",
    "3. Vendor Segmentation\n",
    "\n",
    "Author: Data Science Intern\n",
    "Date: February 2026\n",
    "\"\"\"\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import os\n",
    "from datetime import datetime\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# Import our custom modules\n",
    "from data_preparation import InvoiceDataPreparation\n",
    "from trend_analysis import ExpenseTrendAnalyzer\n",
    "from vendor_segmentation import VendorSegmentation\n",
    "\n",
    "\n",
    "def create_output_directory(base_path='/mnt/user-data/outputs'):\n",
    "    \"\"\"\n",
    "    Create output directory with timestamp.\n",
    "    \n",
    "    Args:\n",
    "        base_path (str): Base directory for outputs\n",
    "        \n",
    "    Returns:\n",
    "        str: Path to created directory\n",
    "    \"\"\"\n",
    "    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')\n",
    "    output_dir = f\"{base_path}/analysis_{timestamp}\"\n",
    "    \n",
    "    os.makedirs(output_dir, exist_ok=True)\n",
    "    \n",
    "    print(f\"📁 Created output directory: {output_dir}\")\n",
    "    \n",
    "    return output_dir\n",
    "\n",
    "\n",
    "def print_section_header(title):\n",
    "    \"\"\"Print a formatted section header.\"\"\"\n",
    "    print(\"\\n\" + \"=\" * 100)\n",
    "    print(f\"{'  ' + title.upper()}\")\n",
    "    print(\"=\" * 100 + \"\\n\")\n",
    "\n",
    "\n",
    "def main():\n",
    "    \"\"\"\n",
    "    Main execution function - runs complete analysis pipeline.\n",
    "    \"\"\"\n",
    "    \n",
    "    # Print welcome banner\n",
    "    print(\"\\n\" + \"🚀\" * 50)\n",
    "    print(\"AINEXTBILL TECHNOLOGY - PURCHASE INVOICE ANALYSIS\")\n",
    "    print(\"Data Science Intern Assignment - Complete Pipeline\")\n",
    "    print(\"🚀\" * 50 + \"\\n\")\n",
    "    \n",
    "    # Configuration\n",
    "    INPUT_FILE = '/mnt/user-data/uploads/purchase_invoices_dataset.xlsx'\n",
    "    OUTPUT_DIR = create_output_directory()\n",
    "    \n",
    "    print(f\"📊 Input file: {INPUT_FILE}\")\n",
    "    print(f\"📁 Output directory: {OUTPUT_DIR}\")\n",
    "    \n",
    "    # =========================================================================\n",
    "    # PHASE 1: DATA PREPARATION\n",
    "    # =========================================================================\n",
    "    \n",
    "    print_section_header(\"PHASE 1: DATA PREPARATION & CLEANING\")\n",
    "    \n",
    "    # Initialize data preparation\n",
    "    prep = InvoiceDataPreparation(filepath=INPUT_FILE)\n",
    "    \n",
    "    # Run full preparation pipeline\n",
    "    cleaned_df = prep.run_full_pipeline(\n",
    "        output_path=f\"{OUTPUT_DIR}/cleaned_invoices.csv\"\n",
    "    )\n",
    "    \n",
    "    print(f\"\\n✅ Phase 1 Complete: Data cleaned and saved\")\n",
    "    print(f\"   Records processed: {len(cleaned_df)}\")\n",
    "    print(f\"   Columns created: {len(cleaned_df.columns)}\")\n",
    "    \n",
    "    # =========================================================================\n",
    "    # PHASE 2: EXPENSE TREND ANALYSIS\n",
    "    # =========================================================================\n",
    "    \n",
    "    print_section_header(\"PHASE 2: EXPENSE TREND ANALYSIS\")\n",
    "    \n",
    "    # Initialize trend analyzer\n",
    "    analyzer = ExpenseTrendAnalyzer(cleaned_df)\n",
    "    \n",
    "    # Run full analysis\n",
    "    trend_results = analyzer.run_full_analysis(\n",
    "        save_visualizations=True,\n",
    "        output_path=OUTPUT_DIR\n",
    "    )\n",
    "    \n",
    "    # Save analysis results\n",
    "    trend_results['monthly_trends'].to_csv(\n",
    "        f\"{OUTPUT_DIR}/monthly_trends.csv\", \n",
    "        index=False\n",
    "    )\n",
    "    \n",
    "    trend_results['category_analysis'].to_csv(\n",
    "        f\"{OUTPUT_DIR}/category_analysis.csv\"\n",
    "    )\n",
    "    \n",
    "    trend_results['vendor_analysis'].to_csv(\n",
    "        f\"{OUTPUT_DIR}/vendor_analysis.csv\"\n",
    "    )\n",
    "    \n",
    "    print(f\"\\n✅ Phase 2 Complete: Trend analysis saved\")\n",
    "    \n",
    "    # =========================================================================\n",
    "    # PHASE 3: VENDOR SEGMENTATION\n",
    "    # =========================================================================\n",
    "    \n",
    "    print_section_header(\"PHASE 3: VENDOR SEGMENTATION (ML)\")\n",
    "    \n",
    "    # Initialize segmentation\n",
    "    segmenter = VendorSegmentation(cleaned_df)\n",
    "    \n",
    "    # Run full segmentation\n",
    "    segment_results = segmenter.run_full_segmentation(\n",
    "        n_clusters=None,  # Auto-detect optimal k\n",
    "        save_outputs=True,\n",
    "        output_path=OUTPUT_DIR\n",
    "    )\n",
    "    \n",
    "    print(f\"\\n✅ Phase 3 Complete: Vendor segmentation saved\")\n",
    "    \n",
    "    # =========================================================================\n",
    "    # FINAL SUMMARY\n",
    "    # =========================================================================\n",
    "    \n",
    "    print_section_header(\"ANALYSIS SUMMARY & KEY INSIGHTS\")\n",
    "    \n",
    "    # Extract key metrics\n",
    "    total_spend = cleaned_df['invoice_amount'].sum()\n",
    "    total_gst = cleaned_df['gst_amount'].sum()\n",
    "    total_invoices = len(cleaned_df)\n",
    "    unique_vendors = cleaned_df['vendor_name'].nunique()\n",
    "    date_range_days = (cleaned_df['invoice_date'].max() - \n",
    "                       cleaned_df['invoice_date'].min()).days\n",
    "    \n",
    "    print(f\"📊 DATASET OVERVIEW:\")\n",
    "    print(f\"   Total invoices: {total_invoices:,}\")\n",
    "    print(f\"   Analysis period: {date_range_days} days ({date_range_days/30:.1f} months)\")\n",
    "    print(f\"   Unique vendors: {unique_vendors}\")\n",
    "    print(f\"   Total spend: ₹{total_spend:,.2f}\")\n",
    "    print(f\"   Total GST: ₹{total_gst:,.2f}\")\n",
    "    print(f\"   Average invoice: ₹{total_spend/total_invoices:,.2f}\")\n",
    "    \n",
    "    # Top insights from analysis\n",
    "    insights = trend_results['insights']\n",
    "    \n",
    "    print(f\"\\n💡 KEY INSIGHTS:\")\n",
    "    print(f\"\\n1️⃣  TOP EXPENSE CATEGORY:\")\n",
    "    print(f\"   {insights['top_category']['name']} - \"\n",
    "          f\"₹{insights['top_category']['spend']:,.2f} \"\n",
    "          f\"({insights['top_category']['percentage']:.1f}% of total)\")\n",
    "    \n",
    "    print(f\"\\n2️⃣  VENDOR CONCENTRATION:\")\n",
    "    print(f\"   Top 3 vendors: {insights['vendor_concentration']:.1f}% of total spend\")\n",
    "    if insights['vendor_concentration'] > 50:\n",
    "        print(f\"   ⚠️  HIGH RISK - Consider vendor diversification\")\n",
    "    \n",
    "    print(f\"\\n3️⃣  SPENDING VOLATILITY:\")\n",
    "    print(f\"   Average MoM change: {insights['monthly_volatility']:.1f}%\")\n",
    "    if insights['monthly_volatility'] > 15:\n",
    "        print(f\"   ⚠️  HIGH VOLATILITY - Improve forecasting and budgeting\")\n",
    "    \n",
    "    print(f\"\\n4️⃣  GST COMPLIANCE OPPORTUNITY:\")\n",
    "    print(f\"   {insights['zero_gst']['count']} invoices with 0% GST\")\n",
    "    print(f\"   Value: ₹{insights['zero_gst']['value']:,.2f}\")\n",
    "    print(f\"   💡 Review for RCM applicability\")\n",
    "    \n",
    "    # Vendor segmentation summary\n",
    "    cluster_summary = segment_results['vendor_features']['cluster_label'].value_counts()\n",
    "    \n",
    "    print(f\"\\n5️⃣  VENDOR SEGMENTATION:\")\n",
    "    for label, count in cluster_summary.items():\n",
    "        cluster_spend = segment_results['vendor_features'][\n",
    "            segment_results['vendor_features']['cluster_label'] == label\n",
    "        ]['total_spend'].sum()\n",
    "        print(f\"   {label}: {count} vendors (₹{cluster_spend:,.2f})\")\n",
    "    \n",
    "    # =========================================================================\n",
    "    # OUTPUT FILES SUMMARY\n",
    "    # =========================================================================\n",
    "    \n",
    "    print_section_header(\"OUTPUT FILES GENERATED\")\n",
    "    \n",
    "    output_files = [\n",
    "        \"cleaned_invoices.csv - Cleaned and standardized dataset\",\n",
    "        \"monthly_trends.csv - Monthly expense aggregations\",\n",
    "        \"category_analysis.csv - Category-wise statistics\",\n",
    "        \"vendor_analysis.csv - Vendor-wise metrics\",\n",
    "        \"vendor_clusters.csv - Vendor segmentation results\",\n",
    "        \"expense_trends_dashboard.png - Visual dashboard\",\n",
    "        \"vendor_clusters_visualization.png - Cluster visualization\",\n",
    "        \"optimal_k_selection.png - Clustering optimization\"\n",
    "    ]\n",
    "    \n",
    "    print(f\"📁 All outputs saved to: {OUTPUT_DIR}\\n\")\n",
    "    for i, file in enumerate(output_files, 1):\n",
    "        print(f\"   {i}. {file}\")\n",
    "    \n",
    "    # =========================================================================\n",
    "    # RECOMMENDATIONS FOR FINANCE TEAM\n",
    "    # =========================================================================\n",
    "    \n",
    "    print_section_header(\"ACTIONABLE RECOMMENDATIONS\")\n",
    "    \n",
    "    print(\"🎯 IMMEDIATE ACTIONS:\")\n",
    "    print(\"\\n1. GST COMPLIANCE:\")\n",
    "    print(\"   • Review 0% GST software invoices for RCM applicability\")\n",
    "    print(\"   • Verify vendor GSTIN for all high-value transactions\")\n",
    "    print(\"   • Set up automated GSTR-2A reconciliation alerts\")\n",
    "    \n",
    "    print(\"\\n2. VENDOR MANAGEMENT:\")\n",
    "    for label, recs in segment_results['recommendations'].items():\n",
    "        print(f\"\\n   {label}:\")\n",
    "        for rec in recs[:2]:  # Top 2 recommendations\n",
    "            print(f\"   {rec}\")\n",
    "    \n",
    "    print(\"\\n3. COST OPTIMIZATION:\")\n",
    "    print(\"   • Negotiate volume discounts with Strategic Partners\")\n",
    "    print(\"   • Consolidate Tactical vendors where possible\")\n",
    "    print(\"   • Review volatile categories for cost reduction\")\n",
    "    \n",
    "    print(\"\\n4. PROCESS IMPROVEMENTS:\")\n",
    "    print(\"   • Automate invoice approval for recurring vendors\")\n",
    "    print(\"   • Set up monthly budget vs actual alerts\")\n",
    "    print(\"   • Implement 90-day cash flow forecasting\")\n",
    "    \n",
    "    # =========================================================================\n",
    "    # COMPLETION\n",
    "    # =========================================================================\n",
    "    \n",
    "    print(\"\\n\" + \"✅\" * 50)\n",
    "    print(\"COMPLETE ANALYSIS PIPELINE FINISHED SUCCESSFULLY!\")\n",
    "    print(\"✅\" * 50 + \"\\n\")\n",
    "    \n",
    "    print(f\"📧 Next Steps:\")\n",
    "    print(f\"   1. Review all outputs in: {OUTPUT_DIR}\")\n",
    "    print(f\"   2. Share insights with CFO/Finance team\")\n",
    "    print(f\"   3. Implement recommended actions\")\n",
    "    print(f\"   4. Schedule monthly analysis runs\")\n",
    "    \n",
    "    return {\n",
    "        'cleaned_data': cleaned_df,\n",
    "        'trend_results': trend_results,\n",
    "        'segment_results': segment_results,\n",
    "        'output_directory': OUTPUT_DIR\n",
    "    }\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    \"\"\"\n",
    "    Execute the main analysis pipeline.\n",
    "    \"\"\"\n",
    "    \n",
    "    try:\n",
    "        results = main()\n",
    "        \n",
    "        print(\"\\n🎉 Analysis completed without errors!\")\n",
    "        print(f\"🎉 All results available in: {results['output_directory']}\")\n",
    "        \n",
    "    except Exception as e:\n",
    "        print(f\"\\n❌ ERROR: Analysis failed\")\n",
    "        print(f\"❌ Error message: {str(e)}\")\n",
    "        \n",
    "        import traceback\n",
    "        print(\"\\n📋 Full traceback:\")\n",
    "        traceback.print_exc()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f33ee9a6-c96f-4682-9261-c8804564f629",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
